### ISSUE TITLE
Checkpoint config file

### ISSUE THREAD

**Issue by hieuvmphan** [yuniw18/Joint_360depth#1]
Hi, I tried training via this command:
`python main.py --train_data Stanford --model_name ./checkpoints/Joint_depth_Table2 ...`

However, it has problem finding the config file: './checkpoints/Joint_depth_Table2/config.txt'. The specific error is `No such file or directory: './checkpoints/default/config.txt'`.

Could you please share with me the config.txt file?

**Comment by yuniw18** [comment]
Hi, `config.txt` is just a file which logs experimental setup. 
It seems that the error occurs because there is no `checkpoints/default` folder in your working directory. 
Try again after making that directoy. Then, `config.txt` file will be made according to the experimental setup.

Thank you
